name: emailservice CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - '.github/workflows/emailservice.yaml'
      # - 'HipsterShopp/hipstershop-shared-workflows/.github/workflows/validation.yaml@main'
      - 'HipsterShopp/hipstershop-shared-workflows/.github/workflows/build.yaml@feature/decouple-workflow'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - '.github/workflows/emailservice.yaml'
      - 'HipsterShopp/hipstershop-shared-workflows/.github/workflows/validation.yaml@feature/decouple-workflow'
      - 'HipsterShopp/hipstershop-shared-workflows/.github/workflows/build.yaml@feature/decouple-workflow'

permissions:
  contents: write


jobs:
  validation:
    uses: HipsterShopp/hipstershop-shared-workflows/.github/workflows/validation.yaml@feature/decouple-workflow
    with:
      github_event_name: ${{ github.event_name }}
      service_name: emailservice
      service_path: src/
      runtime: python
      python-version: "3.11"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build:
    uses: HipsterShopp/hipstershop-shared-workflows/.github/workflows/build.yaml@feature/decouple-workflow
    needs: validation
    if: always() && needs.validation.result == 'success'
    with:
      github_event_name: ${{ github.event_name }}
      service_name: emailservice
      service_path: src/
      runtime: python
      python-version: "3.11"
      sonarqube_result: ${{ needs.validation.outputs.sonarqube_result }}
      snyk_result: ${{ needs.validation.outputs.snyk_result }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  notify:
    uses: HipsterShopp/hipstershop-shared-workflows/.github/workflows/notify.yaml@feature/decouple-workflow
    needs: [validation, build]
    if: |
      always() && (
        needs.validation.result == 'failure' ||
        needs.build.result == 'failure'
      )
    with:
      github_event_name: ${{ github.event_name }}
      service_name: emailservice
      service_path: src/
      runtime: python
      sonarqube_result: ${{ needs.validation.outputs.sonarqube_result }}
      snyk_result: ${{ needs.validation.outputs.snyk_result }}
      generate_tag_result: ${{ needs.build.outputs.generate_tag_result }}
      build_image_result: ${{ needs.build.outputs.build_image_result }}
      trivy_result: ${{ needs.build.outputs.trivy_result }}
      push_result: ${{ needs.build.outputs.push_result }}
      tag: ${{ needs.build.outputs.tag }}
    secrets:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
